### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by Lekensteyn** [h2o/picotls#22]
ASAN reports some memleaks in `x9_62_create_key_exchange`:

```
Direct leak of 48 byte(s) in 1 object(s) allocated from:
    #0 0x7ff375d13e40 in __interceptor_malloc /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:62
    #1 0x40778d in x9_62_create_key_exchange lib/openssl.c:180
    #2 0x40778d in secp256r1_create_key_exchange lib/openssl.c:222
    #3 0x418480 in send_client_hello lib/picotls.c:881
    #4 0x418480 in ptls_handshake lib/picotls.c:2330
    #5 0x405236 in run_handshake t/cli.c:67
    #6 0x405236 in handle_connection t/cli.c:149
    #7 0x4044bf in run_client t/cli.c:336
    #8 0x4044bf in main t/cli.c:507
    #9 0x7ff3751e6290 in __libc_start_main (/usr/lib/libc.so.6+0x20290)
    #10 0x404799 in _start (/tmp/pico/cli+0x404799)
...
SUMMARY: AddressSanitizer: 3089 byte(s) leaked in 52 allocation(s).
```

Reproducer:

    cmake -GNinja ~/projects/picotls -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS=-fsanitize=address
    ninja
    ASAN_OPTIONS=fast_unwind_on_malloc=0 ./cli example.com 443

OpenSSL 1.0.2.j

**Comment by kazuho** [comment]
Thank you for reporting the issue. Fixed in the commit above.
